// pages/index.vue
<template>
  <section>
    <ssrLoader v-if="!isHydrated" :doc="page.doc"></ssrLoader>

    <editor v-if="isHydrated" :doc="page.doc" 
      @docUpdated="updateState($event)">
    </editor>
  </section>
</template>

<script>
import ssrLoader from '~/components/utils/ssr-loader.vue';
import editor from '~/components/editor/editor.vue';

export default {
  components: {
    ssrLoader,
    editor,
  },
  async asyncData({ app }) {
    // @ToDo: fetch page based on slug
    let page = await app.$axios.$get('/api/docs?[$limit]=1')
      .then(res => {
        return res.data[0];
      })
    return { 
      page,
      isHydrated: false,
    };
  },
  mounted() {
    this.isHydrated = true;
  },
  methods: {
    updateState(newDoc) {
      this.page.doc = { ...newDoc };
    },
  },
};
</script>

<style scoped>
section {
  max-width: 720px;
  margin-left: auto;
  margin-right: auto;
}
</style>

// pages/index.jsx
import React from "react";
import axios from "../lib/axios";

import WikiEditor from "../components/editor/editor";

export default class Page extends React.Component {
  static async getInitialProps({ req }) {
    // @ToDo: fetch page based on slug
    let res = await axios.get("/api/docs?$limit=1");
    return { ...res.data.data[0] };
  }

  render() {
    return (
      <React.Fragment>
        <article>
          <WikiEditor doc={this.props} />
        </article>
        <style jsx>{`
          article {
            max-width: 720px;

            margin-top: 24px;
            margin-left: auto;
            margin-right: auto;
          }
        `}</style>
      </React.Fragment>
    );
  }
}
